version: '3.9'

services:
  spring-petclinic-sample:
    image: drill4j/spring-petclinic-sample:0.5.0
    ports:
      - 8087:8080
    environment:
      - JAVA_TOOL_OPTIONS="-agentpath:/data/agent/libdrill_agent.so=drillInstallationDir=/data/agent,adminAddress=host.docker.internal:8090,agentId=ExampleAgent,buildVersion=0.1.0,logLevel=INFO"
    volumes:
      - agent-files:/data
    depends_on:
      agent-files:
        condition: service_completed_successfully

  agent-files:
    image: drill4j/java-agent:0.8.0-29
    volumes:
      - agent-files:/data

volumes:
  agent-files: